service: aws-memorang

provider: 
  name: aws
  runtime: nodejs10.x
  memorySize: 256
  timeout : 15
  stage: production
  region: us-west-2

functions:
  api:
    handler: lambda.handler
    events:   
      - http : 'ANY {proxy+}'
      - http : ANY /